# Generated by Django 2.2.17 on 2020-12-11 01:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('horario', models.CharField(max_length=150, verbose_name='Horarios')),
                ('tel', models.CharField(max_length=50, verbose_name='Teléfono')),
            ],
        ),
        migrations.CreateModel(
            name='Telefono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tel', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contact.Contacto', verbose_name='Teléfono')),
            ],
            options={
                'verbose_name': 'Teléfono',
                'verbose_name_plural': 'Teléfonos',
            },
        ),
    ]
