# Generated by Django 2.2.17 on 2020-12-11 01:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='telefono',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='Teléfono'),
            preserve_default=False,
        ),
    ]
