# Generated by Django 2.2.17 on 2020-12-11 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_telefono_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telefono',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Teléfono'),
        ),
    ]
