# Generated by Django 2.2.17 on 2020-12-11 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20201211_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='category',
            field=models.CharField(max_length=101),
        ),
    ]
