# Generated by Django 2.2.17 on 2020-12-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='noticiaprincipal',
            options={'ordering': ['-created'], 'verbose_name': 'Noticia principal', 'verbose_name_plural': 'Noticia principal'},
        ),
    ]
