# Generated by Django 2.2.17 on 2020-12-10 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20201210_2015'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redsocial',
            options={'verbose_name': 'Redes sociales', 'verbose_name_plural': 'Redes sociales'},
        ),
    ]
