# Generated by Django 2.2.17 on 2020-12-11 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='facebook',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Facebook'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='instagram',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Instagram'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='twitter',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Twitter'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Whatsapp'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='youtube',
            field=models.CharField(blank=True, max_length=400, null=True, verbose_name='Youtube'),
        ),
    ]
